# Generated by Django 5.0 on 2023-12-10 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_pais_country_rename_perfil_profile'),
        ('blog', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Subtitulo'),
        ),
    ]
