# Generated by Django 5.0 on 2023-12-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_author_alter_blog_body_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Experiencia'),
        ),
    ]
