# Generated by Django 5.0 on 2023-12-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_pais_country_rename_perfil_profile'),
        ('blog', '0005_alter_blog_body'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
