# Generated by Django 5.0 on 2023-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_comments_author_alter_comments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=2200),
        ),
    ]
