# Generated by Django 5.0 on 2023-12-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_perfil'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pais',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Profile',
        ),
    ]
