# Generated by Django 5.0 on 2023-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default_avatar.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
