# Generated by Django 5.0 on 2023-12-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
